### ISSUE TITLE
Bug: "flight' is broken: may return the same origin and destination.

### ISSUE THREAD

**Issue by simon-liebehenschel** [dkotschessa/airtravel_faker#2]
Code to reproduce:

```
from faker import Faker
from faker_airtravel import AirTravelProvider


fake = Faker()
for provider in (AirTravelProvider, ):
    fake.add_provider(provider)

for _ in range(10_000):
    random_flight = fake.flight()
    d_iata = random_flight["origin"]["iata"]
    a_iata = random_flight["destination"]["iata"]
    print(f'{random_flight["origin"]} -> {random_flight["destination"]}')
    assert d_iata != a_iata
```

"Origin" and "destination" may be the same.

**UPD:**
You use `random.choices`. It will not give you elements without repetition out of the box. This is why the bug appears.

**Comment by simon-liebehenschel** [comment]
Old:

```python
def flight(self):
        origin, destination = choices(airport_list, k=2)
        airline = choice(airlines)
        stops = choice([1,2,3,'non-stop'])
        price = randint(200, 1000)
        flight_object = {'airline' : airline,
                'origin': origin,
                'destination' : destination,
                'stops' : stops,
                'price' : price
        }
        return flight_object
```

Fixed:

```python
def flight(self):
        origin_index, destination_index = random.sample(range(0, len(airport_list)), 2)
        origin, destination = airport_list[origin_index], airport_list[destination_index]
        airline = choice(airlines)
        stops = choice([1,2,3,'non-stop'])
        price = randint(200, 1000)
        flight_object = {'airline' : airline,
                'origin': origin,
                'destination' : destination,
                'stops' : stops,
                'price' : price
        }
        return flight_object
```

@dkotschessa could you please update the code if the fix is ok for you?

**Comment by dkotschessa** [comment]
> Old:
> 
> ```python
> def flight(self):
>         origin, destination = choices(airport_list, k=2)
>         airline = choice(airlines)
>         stops = choice([1,2,3,'non-stop'])
>         price = randint(200, 1000)
>         flight_object = {'airline' : airline,
>                 'origin': origin,
>                 'destination' : destination,
>                 'stops' : stops,
>                 'price' : price
>         }
>         return flight_object
> ```
> 
> Fixed:
> 
> ```python
> def flight(self):
>         origin_index, destination_index = random.sample(range(0, len(airport_list)), 2)
>         origin, destination = airport_list[origin_index], airport_list[destination_index]
>         airline = choice(airlines)
>         stops = choice([1,2,3,'non-stop'])
>         price = randint(200, 1000)
>         flight_object = {'airline' : airline,
>                 'origin': origin,
>                 'destination' : destination,
>                 'stops' : stops,
>                 'price' : price
>         }
>         return flight_object
> ```
> 
> @dkotschessa could you please update the code if the fix is ok for you?

Yes great point. Though I beleive 

`origin, destination = sample(airport_list, k=2)`

Should be sufficient. I can update in a day or two or you can submit a PR if you'd like. Thank you for using this provider and contributing!

**Comment by simon-liebehenschel** [comment]
> origin, destination = sample(airport_list, k=2)
> 
> Should be sufficient


Yes, I just checked. You are right. Please update this single line of code when you will have some time. Thanks.

**Comment by dkotschessa** [comment]
> > origin, destination = sample(airport_list, k=2)
> > Should be sufficient
> 
> Yes, I just checked. You are right. Please update this single line of code when you will have some time. Thanks.

@AIGeneratedUsername Fix is implemented!  I also added your "reproduce" code as a test.  It is also updated in PyPI.  

 Thanks again!
